✨ feat:
  - base-branch: 'main'

🐛 fix:
  - base-branch: 'main'

🚑 hotfix:
  - base-branch: 'main'

💥 breaking:
  - base-branch: 'main'

⚡ perf:
  - base-branch: 'main'

♻️ refactor:
  - base-branch: 'main'

📝 docs:
  - base-branch: 'main'

✅ test:
  - base-branch: 'main'

💄 style:
  - base-branch: 'main'

🔧 chore:
  - base-branch: 'main'

👷 ci:
  - base-branch: 'main'

🗑️ remove:
  - base-branch: 'main'

⏪ revert:
  - base-branch: 'main'

🚀 release:
  - title: ['^release:']

🏷️ released:
  - base-branch: 'main'
