import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import localFont from 'next/font/local';

import './globals.css';

import { Header } from '@/components';

interface RootLayoutProps {
  children: ReactNode;
}

const pretendard = localFont({
  display: 'swap',
  src: '../../public/fonts/pretendard-variable.woff2',
  variable: '--font-pretendard',
  weight: '45 920',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} antialiased`}>
        <Header />
        <main className="container flex min-h-screen flex-col border-x-1 border-dashed">
          {children}
        </main>
      </body>
    </html>
  );
}
